[package]
name = "satelit-import"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.14.0"
dotenv = "0.13.0"
reqwest = "0.9.15"
config = "0.9.2"
serde = { version = "1.0.90", features = ["derive"] }
diesel = { version = "1.4.2", features = ["sqlite", "r2d2"] }
