[package]
name = "satelit-import"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.14.0"
flate2 = { version = "1.0.7", features = ["tokio"] }

config = "0.9.2"
log = { version = "0.4.6", features = ["std"] }

diesel = { version = "1.4.2", features = ["sqlite", "r2d2"] }
serde = { version = "1.0.90", features = ["derive"] }

reqwest = "0.9.15"
futures = "0.1.26"
tokio = "0.1.19"
tokio-threadpool = "0.1.14"

[dev-dependencies]
tempfile = "3.0.7"
