[package]
name = "satelit-import"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.16.0"
flate2 = { version = "1.0.7", features = ["tokio"] }

config = "0.9.2"
uuid = { version = "0.7.4", features = ["v4"] }
log = { version = "0.4.7", features = ["std"] }
fern = "0.5.8"
lazy_static = "1.4.0"

diesel = { version = "1.4.2", features = ["postgres", "r2d2", "chrono"] }
serde = { version = "1.0.94", features = ["derive"] }

reqwest = "0.9.15"
futures = "0.1.26"
tokio = "0.1.22"
rayon = "1.1.0"

tower-grpc = "0.1.0"
tower-hyper = "0.1.1"
prost = { version = "0.5.0", features = ["prost-derive"] }
bytes = "0.4.12"

[dev-dependencies]
tempfile = "3.1.0"
