[package]
name = "satelit-import"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.15.0"
flate2 = { version = "1.0.7", features = ["tokio"] }

config = "0.9.2"
uuid = { version = "0.7.4", features = ["v4"] }
log = { version = "0.4.8", features = ["std"] }
env_logger = "0.6.2"

diesel = { version = "1.4.2", features = ["sqlite", "r2d2"] }
serde = { version = "1.0.94", features = ["derive"] }

reqwest = "0.9.15"
futures = "0.1.26"
tokio = "0.1.22"
tokio-threadpool = "0.1.15"

tower-grpc = "0.1.0"
tower-hyper = "0.1.0"
prost = { version = "0.5.0", features = ["prost-derive"] }
bytes = "0.4.12"

[dev-dependencies]
tempfile = "3.1.0"
