[package]
name = "satelit-import"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.16.0"
flate2 = { version = "1.0.7", features = ["tokio"] }

config = "0.9.2"
log = { version = "0.4.7", features = ["std"] }
lazy_static = "1.4.0"
chrono = "0.4.7"

diesel = { version = "1.4.2", features = ["postgres", "r2d2", "chrono"] }
serde = { version = "1.0.94", features = ["derive"] }

reqwest = "0.9.15"
futures = "0.1.26"
tokio = "0.1.22"
rayon = "1.1.0"

tower-grpc = "0.1.0"
tower-hyper = "0.1.1"
prost = { version = "0.5.0", features = ["prost-derive"] }
bytes = "0.5.4"

[dev-dependencies]
tower = "0.1.1"
hyper = "0.12.33"
tower-request-modifier = "0.1.0"
tempfile = "3.1.0"
toml = "0.4.10"
