[package]
name = "satelit-import"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.14.0"

config = "0.9.2"

diesel = { version = "1.4.2", features = ["sqlite", "r2d2"] }
serde = { version = "1.0.90", features = ["derive"] }

reqwest = "0.9.15"
futures = "0.1.26"
tokio = "0.1.19"
