[package]
name = "satelit-import"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.17.2"
flate2 = { version = "1.0.13", features = ["tokio"] }

config = "0.10.1"
log = { version = "0.4.8", features = ["std"] }
lazy_static = "1.4.0"
chrono = "0.4.10"

diesel = { version = "1.4.3", features = ["postgres", "r2d2", "chrono"] }
serde = { version = "1.0.104", features = ["derive"] }

futures = "0.3.4"
tokio = { version = "0.2.13", features = ["fs"] }
tracing = "0.1.13"
tracing-futures = "0.2.3"
tracing-subscriber = "0.2.3"

tonic = "0.1.1"
prost = "0.6.1"
reqwest = { version = "0.10.4", features = ["gzip"] }

[dev-dependencies]
tower = "0.1.1"
hyper = "0.12.33"
tower-request-modifier = "0.1.0"
tempfile = "3.1.0"
toml = "0.4.10"
