[db]
path = "db/anime.sqlite"
max-connections = 8
connection-timeout = 15

[anidb]
dump-url = "http://anidb.net/api/anime-titles.xml.gz"
download-path = "db/anidb-dump/dump.gz"
last-dump = "db/anidb-dump/last.xml"
new-dump = "db/anidb-dump/new.xml"
