[db]
{{ if db }}
# PG_DB_URL
url = "{ db.url }"
{{ else }}
url = "postgres://postgres@localhost/satelit_import"
{{ endif }}

max_connections = 64
connection_timeout = 30

[rpc]
port = 9060

[storage]
{{ if storage }}
# DO_SPACES_HOST
host = "{ storage.host }"

# DO_BUCKET
bucket = "{ storage.bucket }"

# DO_SPACES_REGION
region = "{ storage.region }"

# DO_SPACES_KEY
key = "{ storage.key }"

# DO_SPACES_SECRET
secret = "{ storage.secret }"
{{ else }}
host = "localhost:9000"
bucket = "satelit"
region = "local"
key = "AKIAIOSFODNN7EXAMPLE"
secret = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
{{ endif }}
