[db]
path = "db/anime.sqlite"
max_connections = 8
connection_timeout = 15

[import]
download_path = "db/anidb-dump/dump.gz"
dump_backup_path = "db/anidb-dump/old.xml"
dump_path = "db/anidb-dump/new.xml"
