[db]
path = "resources/tests/tmp/anime.sqlite"

[import]
dump_url = "http://localhost:8080/static"
download_path = "resources/tests/tmp/dump.gz"
old_dump_path = "resources/tests/tmp/old.xml"
dump_path = "resources/tests/tmp/new.xml"
reimport_track_path = "resources/tests/tmp/reimport.txt"
